"""update migration

Revision ID: 085e848c6a7d
Revises: a2ad5e587046
Create Date: 2024-07-10 20:51:40.721600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085e848c6a7d'
down_revision = 'a2ad5e587046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
