"""update migration

Revision ID: 0b815adb4279
Revises: 
Create Date: 2024-07-13 21:28:44.974997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b815adb4279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('car_image', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], name=op.f('fk_vehicles_owner_id_owners')),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('features',
    sa.Column('feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('speed_km', sa.String(), nullable=False),
    sa.Column('car_cc', sa.Integer(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], name=op.f('fk_features_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('feature_id')
    )
    op.create_table('rentals',
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('rental_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], name=op.f('fk_rentals_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('rental_id')
    )
    op.create_table('vehicle_features',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.feature_id'], name=op.f('fk_vehicle_features_feature_id_features')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], name=op.f('fk_vehicle_features_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('vehicle_id', 'feature_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_features')
    op.drop_table('rentals')
    op.drop_table('features')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('owners')
    # ### end Alembic commands ###
