"""update migration

Revision ID: 2a3f35aeaec2
Revises: 085e848c6a7d
Create Date: 2024-07-10 21:31:32.639930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3f35aeaec2'
down_revision = '085e848c6a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('car_cc',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.alter_column('car_cc',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
