"""update migration

Revision ID: a2ad5e587046
Revises: c69987848e74
Create Date: 2024-07-10 14:46:00.961434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ad5e587046'
down_revision = 'c69987848e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_features_vehicle_id_vehicles'), 'vehicles', ['vehicle_id'], ['vehicle_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_features_vehicle_id_vehicles'), type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###
